import '../../routes/routes'
import '../../lib/vendor/jquery.validationEngine'
import '../../lib/vendor/jquery.validationEngine-en'
import '../../custom/home/client/index'
import '../../layout/index'
import '../../custom/roles/client/index'
import '../../custom/login/client/index'
import '../../custom/register/client/index'